### PR TITLE
logo change and session issue update

### PR DESCRIPTION
**Pull request by sravanthikalluri19**

### CODE REVIEW

**Comment by rahlvers** [comment]
@anandnagraj - please check session cleanup fix

**Comment by rahlvers** [comment]
Pull to address issue #5 and #11

**Comment by anandnagraj** [comment]
I checked Swordfish_07-02-2018 and it does not fix #11 . #5 has been fixed. I also could not see changes relevant to #11. The file changes are all around the swordfish logo.

**Comment by rahlvers** [comment]
Approved by SSM TWG review.

**Pull request merged**
