### PR TITLE
SNIA Swordfish basic webclient docs

### PR DESCRIPTION
**Pull request by sravanthikalluri19**
SNIA basic web client documentation's for
1. General audience
2.Developer
3.Installation steps(Environment Set up)

### CODE REVIEW

**Comment by rahlvers** [comment]
Waiting for additional comments in developer doc to be addressed RE: how to modify GUI code when new, updated Redfish / Swordfish schemaare available.  Also, where in the GUI code, specifically, are the schema referenced?

**Comment by rahlvers** [comment]
Latest updates to documentation still don't show any reference to schema, only to extracting information from the service.  I've embedded both changes and comments. @sravanthikalluri19 - please review and update.

**Comment by ddeel** [comment]
Has there been any progress towards addressing the comments on this pull request?

**Comment by sravanthikalluri19** [comment]
@rahlvers @ddeel 

please clarify the below points
 `1. This section doesn’t describe how the system references the schema.  It only describes how it interacts with running services.`
 

> Hoping the running services are designed and implemented based on the schema's

`2.  How does the web client decide which properties are editable?  `

>     Based on the schema definition if the properties are editable, the services are appending a permissions property containing Boolean values for read and write. 

Apart from these do we need to add/change any functionality/points in the document?

**Comment by rahlvers** [comment]
The documentation needs to be cleaned up to remove all references to schema - the web client doesn't look at schema at all.  It only interacts with the service.

**Comment by rahlvers** [comment]
Approved in SSM TWG 9/11/18

**Pull request merged**
