### PR TITLE
changes related to #22 and #21 - copyright fixes and spelling errors

### PR DESCRIPTION
**Pull request by sravanthikalluri19**

### CODE REVIEW

**Comment by sravanthikalluri19** [comment]
changes related to issues #22 and #21

**Comment by sravanthikalluri19** [comment]
replaced copyright information form 2018 to 2017-2018

**Comment by rahlvers** [comment]
@sravanthikalluri19 - Put unrelated changes into separate pull requests.

**Comment by sravanthikalluri19** [comment]
sure @rahlvers

**Comment by rahlvers** [comment]
Reviewed and approved as an editorial review - RA / DD.  5/24/18

**Pull request merged**
