### PR TITLE
#30 - Does not add items to Redfish collections

### PR DESCRIPTION
**Pull request by sravanthikalluri19**
code added to validate the response even though status code is not present

### CODE REVIEW

**Comment by ddeel** [comment]
This pull request does not fix or improve the "Add Items to Redfish collections" problem (#30 ), and it actually makes things worse, because the client is no longer able to remove objects from collections.

The previous version of the client was able to successfully remove objects from collections, but this version of the client always gets a "Deleting a service Failed" message when Remove operations are attempted, and this happens with both Swordfish and Redfish objects.

There is no change to the client behavior for attempts to add objects to Redfish collections. It still does the same things reported in Issue #30  .

**Comment by sravanthikalluri19** [comment]
Reverted the changes back for delete a item from existing collection.
Checked all possibilities to catch error/success code  form api.
Able to successfully add/delete item from StorageServices and StorageSystems collections

**Comment by ddeel** [comment]
The most recent code for this pull request restores the ability to delete items from Redfish and Swordfish collections, but the client is still not able to add items to Redfish collections. Attempts to add items to Redfish collections result in this message: "Error :Adding a new collection/service failed at this moment".

**Comment by rahlvers** [comment]
Approved in SSM TWG meeting. 7/3/18

**Pull request merged**
