### PR TITLE
pull request for #17

### PR DESCRIPTION
**Pull request by sravanthikalluri19**
[storageservices_unittestdocx.docx](https://github.com/SNIA/Swordfish-basic-web-client/files/1785570/storageservices_unittestdocx.docx)
#16 is working fine in our local systems, please see attached unittest docx . let us know if any issues .

### CODE REVIEW

**Comment by dorado18** [comment]
Is there some log information that I can send to you for your analysis? I used both branches master and Web-client_03-06-2018 but I still cant get the navigation links clickable.
There are some differences in our clients, in the image you attached, you don't have a pane titled "Members('4FDB0851-EE73-C655-0D13-A2A7F8A4F7AA')", your "StorageServices" pane shows the navigation, while mine only have a clickable "Members('4FDB0851-EE73-C655-0D13-A2A7F8A4F7AA')".

**Comment by dorado18** [comment]
I did the rebuild, but the behaviour is still the same for me.

**Comment by sravanthikalluri19** [comment]
@dorado18 if possible can we have a meeting so that we can find out the root cause.

**Comment by dorado18** [comment]
How would be that?

**Pull request merged**
